sudo: false
language: python
before_install:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GH_TOKEN" -d "{\"state\":\"pending\",\"description\":\"Dependent build
    created\",\"context\":\"continuous-integration/travis-ci/python-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/9bf73e73d9938188cdbd59ca748639bb6263a83a'
  - node --version
  - npm link --python=python2 ./__dredd__
  - bundle install
  - npm install npm@latest
python: '3.5'
script:
  - python -B -m unittest discover
  - pip install -e .
  - bundle exec cucumber
env:
  global:
    secure: >-
      E/BLX3YIDdYV5saL0W4gnUkSe658yei9nMTVyCZpqRjSatui8NFty+zwlaJ1t7344vZ0mG8ZVrCJYtCiR+RwLwN/f/fWiLTO9cTCMNwUy3aqLt/Gx3CQWqZ2UGTRhWrVwV/WAtOkyg5mSZL+HG8I3kNy303VRvXVBXAg+/7GG5Y=
after_failure:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GH_TOKEN" -d "{\"state\":\"error\",\"description\":\"Dependent build
    finished\",\"context\":\"continuous-integration/travis-ci/python-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/9bf73e73d9938188cdbd59ca748639bb6263a83a'
after_success:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GH_TOKEN" -d "{\"state\":\"success\",\"description\":\"Dependent build
    finished\",\"context\":\"continuous-integration/travis-ci/python-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/9bf73e73d9938188cdbd59ca748639bb6263a83a'
  - >-
    if [[ $TRAVIS_BRANCH = master ]]; then echo "Deleting aborted (master)" &&
    exit 1; fi
  - git branch -D $TRAVIS_BRANCH
  - >-
    git remote set-url origin "https://$GH_TOKEN@github.com/apiaryio/dredd.git"
    > /dev/null 2>&1
  - git push origin -f --delete $TRAVIS_BRANCH > /dev/null 2>&1
